### ISSUE TITLE
不管选择何种翻译方式都会报错

### ISSUE THREAD

**Issue by PantsuDango** [xd2333/GalTransl#101]
```shell

   ____       _ _____                    _
  / ___| __ _| |_   _| __ __ _ _ __  ___| |
 | |  _ / _` | | | || '__/ _` | '_ \/ __| |
 | |_| | (_| | | | || | | (_| | | | \__ \ |
  \____|\__,_|_| |_||_|  \__,_|_| |_|___/_|

------Translate your favorite Galgame------

Ver: 5.2.0
Author: xd2333
Contributors: ryank231231, PiDanShouRouZhouXD, Noriverwater, Isotr0py, adsf0427, pipixia244, gulaodeng

请输入/拖入项目文件夹，或项目文件夹内的yaml配置文件：E:\GalTransl\露出プレイ少女２
------------------------------------------------------------------------------------------------------------------------请为『露出プレイ少女２』项目选择翻译器：sakura-009
[06-16 12:20:14][WARNING]未找到文本插件: (project_dir)text_common_example，跳过该插件
[06-16 12:20:14][INFO]加载插件"通用-译后常规修复"...
RetryError[<Future at 0x21a736806b0 state=finished raised ConnectError>]
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 69, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 373, in handle_async_request
  File "httpcore\_async\connection_pool.py", line 216, in handle_async_request
  File "httpcore\_async\connection_pool.py", line 196, in handle_async_request
  File "httpcore\_async\http_proxy.py", line 207, in handle_async_request
  File "httpcore\_async\connection.py", line 99, in handle_async_request
  File "httpcore\_async\connection.py", line 76, in handle_async_request
  File "httpcore\_async\connection.py", line 122, in _connect
  File "httpcore\_backends\auto.py", line 30, in connect_tcp
  File "httpcore\_backends\anyio.py", line 114, in connect_tcp
  File "contextlib.py", line 158, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tenacity\_asyncio.py", line 61, in __call__
  File "GalTransl\ConfigHelper.py", line 168, in _availablityChecker
  File "httpx\_client.py", line 1801, in get
  File "httpx\_client.py", line 1574, in request
  File "httpx\_client.py", line 1661, in send
  File "httpx\_client.py", line 1689, in _send_handling_auth
  File "httpx\_client.py", line 1726, in _send_handling_redirects
  File "httpx\_client.py", line 1763, in _send_single_request
  File "httpx\_transports\default.py", line 372, in handle_async_request
  File "contextlib.py", line 158, in __exit__
  File "httpx\_transports\default.py", line 86, in map_httpcore_exceptions
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GalTransl\__main__.py", line 32, in worker
  File "asyncio\runners.py", line 194, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 685, in run_until_complete
  File "GalTransl\Runner.py", line 139, in run_galtransl
  File "GalTransl\ConfigHelper.py", line 190, in checkAvailablity
  File "tenacity\_asyncio.py", line 142, in async_wrapped
  File "tenacity\_asyncio.py", line 58, in __call__
  File "tenacity\_asyncio.py", line 110, in iter
  File "tenacity\_asyncio.py", line 78, in inner
  File "tenacity\__init__.py", line 411, in exc_check
tenacity.RetryError: RetryError[<Future at 0x21a736806b0 state=finished raised ConnectError>]
请按任意键继续. . .
```

**Comment by xd2333** [comment]
代理不通导致的，检查下代理或直接关掉。后面会优化这块的提示信息

**Comment by PantsuDango** [comment]
> 代理不通导致的，检查下代理或直接关掉。后面会优化这块的提示信息

非常感谢回复！~
我确实在config.yaml里设置了如下的proxy配置
```yaml
# 代理设置
proxy:
  enableProxy: true # 是否启用代理。[True/False]
  proxies:
    - address: http://127.0.0.1:7890
# 字典设置，所有字典、字典内词条将按顺序从上到下替换
```
但是我调用的是本地的 sakura-009 模型，它也会走代理去调用么？

**Comment by xd2333** [comment]
> > 代理不通导致的，检查下代理或直接关掉。后面会优化这块的提示信息
> 
> 非常感谢回复！~ 我确实在config.yaml里设置了如下的proxy配置
> 
> ```yaml
> # 代理设置
> proxy:
>   enableProxy: true # 是否启用代理。[True/False]
>   proxies:
>     - address: http://127.0.0.1:7890
> # 字典设置，所有字典、字典内词条将按顺序从上到下替换
> ```
> 
> 但是我调用的是本地的 sakura-009 模型，它也会走代理去调用么？

目前即使不走代理也会检测可用性，这里是检测代理可用性报错了，后面改一改
