### ISSUE TITLE
启动该翻译程序时报错

### ISSUE THREAD

**Issue by ZKENSS** [xd2333/GalTransl#115]
不会代码，这种该如何解决？

请为『TASK』项目选择翻译器：gpt35-1106
[07-07 09:11:46][INFO]加载插件"通用-译后常规修复"...
string indices must be integers, not 'str'
Traceback (most recent call last):
  File "E:\TASK\GalTransl-v5.4.1\GalTransl\__main__.py", line 32, in worker
    run(run_galtransl(cfg, translator))
  File "C:\Users\Zken\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Zken\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zken\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\TASK\GalTransl-v5.4.1\GalTransl\Runner.py", line 138, in run_galtransl
    proxyPool = CProxyPool(cfg) if cfg.getKey("internals.enableProxy") else None
                ^^^^^^^^^^^^^^^
  File "E:\TASK\GalTransl-v5.4.1\GalTransl\ConfigHelper.py", line 162, in __init__
    (False, CProxy(i["address"], i.get("username", i.get("password"))))
                   ~^^^^^^^^^^^

**Comment by xd2333** [comment]
代理设置部分配错了，可以重新配置以下，或者不使用代理

**Comment by ZKENSS** [comment]
确实是代理出了问题。
