### ISSUE TITLE
请问“单次翻译句子数量”是指“一次请求”所翻译的句子数量吗？

### ISSUE THREAD

**Issue by TonokoTakatsuki** [XD2333/GalTransl#2]
那样的话，理论上是否单次翻译句子数量越多，就能在newbing每天200次请求的额度内翻译更多的句子？

我的测试貌似一次15句左右是极限，再往上就会出错。

想用newbing翻译H的话，单次翻译句子数量填为1就可以了，不过不知道这样是不是会太浪费额度了

还望大佬解答，非常感谢！

**Comment by XD2333** [comment]
是的。

太多效果不好，太少浪费。

一个推荐的技巧是先设置`num_pre_request`为9或12，翻译一遍后，

设置`retry_fail`为True，设置`num_pre_request`为3，再跑一遍

至于最后要不要设置成1，看心情了（

**Comment by TonokoTakatsuki** [comment]
> 是的。
> 
> 太多效果不好，太少浪费。
> 
> 一个推荐的技巧是先设置`num_pre_request`为9或12，翻译一遍后，
> 
> 设置`retry_fail`为True，设置`num_pre_request`为3，再跑一遍
> 
> 至于最后要不要设置成1，看心情了（

感谢解答。
主要是gpt3.5那个好像不支持我电脑的python版本（3.8），所以翻译H比较麻烦（悲）

**Comment by XD2333** [comment]
> > 是的。
> > 太多效果不好，太少浪费。
> > 一个推荐的技巧是先设置`num_pre_request`为9或12，翻译一遍后，
> > 设置`retry_fail`为True，设置`num_pre_request`为3，再跑一遍
> > 至于最后要不要设置成1，看心情了（
> 
> 感谢解答。 主要是gpt3.5那个好像不支持我电脑的python版本（3.8），所以翻译H比较麻烦（悲）
> 
> 另外想请问一下大佬，能否有办法暂时跳过H的内容，直接保留日语原文？

目前没有。如果你的翻的脚本有区分h的话（例如带_h等），可以先把那些json_jp剪切出去。如果都混在一块那就没办法了。
最低python要求应该是3.9，是不能升级吗？这么怪的环境233

**Comment by TonokoTakatsuki** [comment]
> > > 是的。
> > > 太多效果不好，太少浪费。
> > > 一个推荐的技巧是先设置`num_pre_request`为9或12，翻译一遍后，
> > > 设置`retry_fail`为True，设置`num_pre_request`为3，再跑一遍
> > > 至于最后要不要设置成1，看心情了（
> > 
> > 
> > 感谢解答。 主要是gpt3.5那个好像不支持我电脑的python版本（3.8），所以翻译H比较麻烦（悲）
> > 另外想请问一下大佬，能否有办法暂时跳过H的内容，直接保留日语原文？
> 
> 目前没有。如果你的翻的脚本有区分h的话（例如带_h等），可以先把那些json_jp剪切出去。如果都混在一块那就没办法了。 最低python要求应该是3.9，是不能升级吗？这么怪的环境233

H是混在一起的，看样子是无解了（

newbing3.8也可以跑，gpt3.5不行。

主要是我用的另一个项目对python版本有要求，而且装了一堆依赖，升级起来有点麻烦2333

ps.刚刚想了想还是升级了，现在运行一切正常，感谢大佬~~~

**Comment by yuaniyuan** [comment]
> 那样的话，理论上是否单次翻译句子数量越多，就能在newbing每天200次请求的额度内翻译更多的句子？
> 
> 我的测试貌似一次15句左右是极限，再往上就会出错。
> 
> 想用newbing翻译H的话，单次翻译句子数量填为1就可以了，不过不知道这样是不是会太浪费额度了
> 
> 还望大佬解答，非常感谢！

老哥，为啥我的bing调用就报403拒绝链接啊，cookie明明写了
Traceback (most recent call last):
  File "E:\My\game\gal\BISHOP\机翻工具包\GalTransl-main\GalTransl\Backend\BingGPT4Translate.py", line 137, in translate
    async for final, response in self.chatbot.ask_stream(
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 155, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\chathub.py", line 86, in ask_stream
    async with wss_session.ws_connect(
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
[2023-06-16 13:36:18,925][INFO]->请求次数：2

[2023-06-16 13:36:18,925][INFO]->输出：

[2023-06-16 13:36:19,714][INFO]Error:403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub'), Please wait 30 seconds
Traceback (most recent call last):
  File "E:\My\game\gal\BISHOP\机翻工具包\GalTransl-main\GalTransl\Backend\BingGPT4Translate.py", line 137, in translate
    async for final, response in self.chatbot.ask_stream(
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 155, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\chathub.py", line 86, in ask_stream
    async with wss_session.ws_connect(
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\28611\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
[2023-06-16 13:36:24,716][INFO]->请求次数：3
