### ISSUE TITLE
遇到一个bug，如果「」文本框里面为空，则会出现整个文本文件都读取失败的情况

### ISSUE THREAD

**Issue by lwzaaz** [XD2333/GalTransl#20]
![4W)CI_BP@@M)X)F%2Q5UH)S](https://github.com/XD2333/GalTransl/assets/44052108/63f232be-69de-4822-aab5-2d67c2fad44e)
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\GalTransl-core\run_GalTransl.py", line 37, in <module>
    run_galtransl(cfg, translator)
  File "C:\Users\Administrator\Desktop\GalTransl-core\GalTransl\Runner.py", line 14, in run_galtransl
    doGPT3Translate(cfg, type="unoffapi")
  File "C:\Users\Administrator\Desktop\GalTransl-core\GalTransl\Frontend\GPT.py", line 120, in doGPT3Translate
    doGPT3TranslateSingleFile(
  File "C:\Users\Administrator\Desktop\GalTransl-core\GalTransl\Frontend\GPT.py", line 42, in doGPT3TranslateSingleFile
    tran.analyse_dialogue()  # 解析是否为对话
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\GalTransl-core\GalTransl\CSentense.py", line 70, in analyse_dialogue
    and ord(last_symbol) - ord(first_symbol) == 1  # 是同一对
        ^^^^^^^^^^^^^^^^
TypeError: ord() expected a character, but string of length 0 found
错误提示如上

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/2.3.3
