### ISSUE TITLE
不明原因停止

### ISSUE THREAD

**Issue by 15119862224** [XD2333/GalTransl#22]
Traceback (most recent call last):
  File "D:\HKR_v121\GalTransl2.3.3\run_GalTransl.py", line 37, in <module>
    run_galtransl(cfg, translator)
  File "D:\HKR_v121\GalTransl2.3.3\GalTransl\Runner.py", line 18, in run_galtransl
    doNewBingTranslate(cfg)
  File "D:\HKR_v121\GalTransl2.3.3\GalTransl\Frontend\GPT.py", line 286, in doNewBingTranslate
    gptapi.batch_translate(
  File "D:\HKR_v121\GalTransl2.3.3\GalTransl\Backend\BingGPT4Translate.py", line 382, in batch_translate
    num, trans_result = asyncio.run(
                        ^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\HKR_v121\GalTransl2.3.3\GalTransl\Backend\BingGPT4Translate.py", line 303, in translate
    await self._change_cookie()
  File "D:\HKR_v121\GalTransl2.3.3\GalTransl\Backend\BingGPT4Translate.py", line 424, in _change_cookie
    self.chatbot = await Chatbot.create(
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\EdgeGPT\conversation.py", line 103, in create
    response = await client.get(
               ^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 261, in handle_async_request
    raise exc
  File "D:\Python Files\python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpcore\_async\http_proxy.py", line 271, in handle_async_request
    connect_response = await self._connection.handle_async_request(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpcore\_async\connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpcore\_async\connection.py", line 117, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpcore\backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\httpcore\backends\asyncio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\site-packages\anyio\_core\_sockets.py", line 221, in connect_tcp
    await event.wait()
  File "D:\Python Files\python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 1778, in wait
    if await self._event.wait():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python Files\python311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

D:\HKR_v121\GalTransl2.3.3>pause
请按任意键继续. . .

**Comment by XD2333** [comment]
试一下是否有改善
https://github.com/XD2333/GalTransl/releases/tag/2.4.0
