### ISSUE TITLE
好像有Bug

### ISSUE THREAD

**Issue by wxq123qw555** [XD2333/GalTransl#3]
报错代码
Traceback (most recent call last):
  File "c:\Users\Desktop\cqb\chat\项目示例\ChatGPT项目示例\run_galtransl.py", line 27, in <module>
    transl_api.batch_translate(
  File "c:\Users\Desktop\cqb\chat\项目示例\ChatGPT项目示例\chatgpt_transl_api.py", line 236, in batch_translate
    trans_result = asyncio.run(
                   ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\Desktop\cqb\chat\项目示例\ChatGPT项目示例\chatgpt_transl_api.py", line 186, in chatgpt_translate
    if result[key_name].startswith("\r\n") and not trans_list[

**Comment by XD2333** [comment]
报错没截全，这个只是错误位置，还有个ERROR：也需要

**Comment by wxq123qw555** [comment]
完整的
Traceback (most recent call last):
  File "c:\Users\Desktop\cqb\chat\项目示例\ChatGPT项目示例\run_galtransl.py", line 27, in <module>
    transl_api.batch_translate(
  File "c:\Users\Desktop\cqb\chat\项目示例\ChatGPT项目示例\chatgpt_transl_api.py", line 236, in batch_translate
    trans_result = asyncio.run(
                   ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\Desktop\cqb\chat\项目示例\ChatGPT项目示例\chatgpt_transl_api.py", line 186, in chatgpt_translate
    if result[key_name].startswith("\r\n") and not trans_list[
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'startswith'
PS C:\Users\Desktop>
