### ISSUE TITLE
使用gpt3.5模拟网页端操作时报错

### ISSUE THREAD

**Issue by Ptilopsis01** [XD2333/GalTransl#47]
```
翻译器：chatgpt-gpt35
[2023-11-06 16:27:58,516][INFO]载入 00通用字典_译前.txt  26普通；
[2023-11-06 16:27:58,516][INFO]载入 01H字典_矫正_译前.txt  145普通；
[2023-11-06 16:27:58,516][INFO]载入 00通用字典_符号_译后.txt  9普通；23条件；
[2023-11-06 16:27:58,516][INFO]载入 00通用字典_译后.txt  1普通；5条件；
[2023-11-06 16:27:58,516][INFO]载入 GPT字典: GPT字典.txt 7个词条
[2023-11-06 16:27:58,518][INFO]载入 GPT字典: 项目GPT字典.txt 8个词条
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)    
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='bypass.churchless.tech', port=443): Max retries exceeded with url: /conversations (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\GalTransl\run_GalTransl.py", line 37, in <module>
    run_galtransl(cfg, translator)
  File "F:\GalTransl\GalTransl\Runner.py", line 14, in run_galtransl
    doGPT3Translate(cfg, type="unoffapi")
  File "F:\GalTransl\GalTransl\Frontend\GPT.py", line 110, in doGPT3Translate
    gptapi = CGPT35Translate(projectConfig, type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GalTransl\GalTransl\Backend\GPT3Translate.py", line 143, in __init__
    self.chatbot.clear_conversations()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 102, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\revChatGPT\V1.py", line 1005, in clear_conversations
    response = self.session.patch(url, data='{"is_visible": false}')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 661, in patch
    return self.request("PATCH", url, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='bypass.churchless.tech', port=443): Max retries exceeded with url: /conversations (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
```

报错内容如上所示，已经安装了相关依赖项，py版本为3.11.6

**Comment by Ptilopsis01** [comment]
补充一下，使用new bing时似乎也是同样的报错

**Comment by XD2333** [comment]
模拟网页操作模式已经寄了，openai的人机识别技术太强（
