### ISSUE TITLE
gpt4 报错

### ISSUE THREAD

**Issue by hyominli** [XD2333/GalTransl#56]
![image](https://github.com/XD2333/GalTransl/assets/26926749/f9d8b6c1-f3a7-4697-a9f3-26d629a3fd37)

[2023-12-16 09:42:43,310][INFO]->输出：
[2023-12-16 09:42:46,321][ERROR]-> 400 bad request {"error":{"message":"max_tokens is too large: 6151. this model supports at most 4096 completion tokens, whereas you provided 6151. (request id: 20231216014244983811118aaztsald) (request id: 20231216014244797273456z8koew4k) (request id: 20231216094244703802638pwrldvix) (request id: 20231216094244672886887sivpsufv)","type":"invalid_request_error","param":"","code":null}}
[2023-12-16 09:42:46,321][ERROR]-> 报错, 5秒后重试
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\GPT4Translate.py", line 242, in translate
    for data in self.chatbot.ask_stream(prompt_req):
  File "C:\Users\hyominli\AppData\Local\Programs\Python\Python310\lib\site-packages\revChatGPT\V3.py", line 244, in ask_stream
    raise t.APIConnectionError(
revChatGPT.typings.APIConnectionError: 400 Bad Request {"error":{"message":"max_tokens is too large: 6151. This model supports at most 4096 completion tokens, whereas you provided 6151. (request id: 20231216014244983811118AaZTsAld) (request id: 20231216014244797273456Z8koEw4K) (request id: 20231216094244703802638pwrldVIx) (request id: 20231216094244672886887sIvpsuFv)","type":"invalid_request_error","param":"","code":null}}

**Comment by XD2333** [comment]
fix in v3.3.0
