### ISSUE TITLE
最新release中newbing报错

### ISSUE THREAD

**Issue by Ptilopsis01** [XD2333/GalTransl#57]
```
翻译器：newbing
[2023-12-18 00:41:39,302][INFO]HTTP Request: GET http://www.gstatic.com/generate_204 "HTTP/1.1 204 No Content"
[2023-12-18 00:41:39,303][INFO]载入 00通用字典_译前.txt  26普通；
[2023-12-18 00:41:39,305][INFO]载入 01H字典_矫正_译前.txt  145普通；
[2023-12-18 00:41:39,306][INFO]载入 00通用字典_符号_译后.txt  9普通；23条件；
[2023-12-18 00:41:39,306][INFO]载入 00通用字典_译后.txt  1普通；5条件；
[2023-12-18 00:41:39,307][INFO]载入 GPT字典: GPT字典.txt 7个词条
[2023-12-18 00:41:39,307][INFO]载入 GPT字典: 项目GPT字典.txt 8个词条
[2023-12-18 00:41:39,307][WARNING]不使用代理
'<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\__main__.py", line 27, in worker
    run(run_galtransl(cfg, translator))
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "F:\GalTransl\GalTransl\Runner.py", line 32, in run_galtransl
    await doNewBingTranslate(cfg, proxyPool)
  File "F:\GalTransl\GalTransl\Frontend\GPT.py", line 418, in doNewBingTranslate
    semaphore = Semaphore(projectConfig.getKey("workersPerProject"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\asyncio\locks.py", line 347, in __init__
    if value < 0:
       ^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
尝试了3.10.11和3.11.6的py，报错相同

**Comment by Ptilopsis01** [comment]
破案了，是我没把配置文件改成新的
但是new bing还是不可用，和 #44 情况相同

**Comment by kzprkzzcu** [comment]
找一个EdgeGPT的最近更新的fork项目替换掉原来的就好了

**Comment by Ptilopsis01** [comment]
> 找一个EdgeGPT的最近更新的fork项目替换掉原来的就好了

好我试试

**Comment by kzprkzzcu** [comment]
> 破案了，是我没把配置文件改成新的 但是new bing还是不可用，和 #44 情况相同

这个issue里，E-Chen的ReEdgeGPT项目是可用的。在BingGPT4Translate.py文件中，只需要把`from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle`改成`from re_edge_gpt import Chatbot, ConversationStyle`
还有几点注意事项：
1.请确保cookie是可以使用的，先用你的账号登上newbing，创建会话随便输入些内容，等newbing回复后再获取cookie。
2.GalTransl使用newbing翻译时，请使用全局代理，不要用亚洲节点，用欧美节点，否则会报连接错误。
3.BingGPT4Translate.py文件有些地方要修改，82行加上：
```
# 记录确信度
if val := config.getKey("gpt.recordConfidence"):
    self.record_confidence = val
else:
    self.record_confidence = False
```
不然会报错。还有394行的`await self._change_cookie()`建议注释掉，否则会进行多余的换cookie操作

**Comment by Ptilopsis01** [comment]
好好好可用了，非常感谢

> 不然会报错。还有394行的`await self._change_cookie()`建议注释掉，否则会进行多余的换cookie操作

顺便这个是399行

**Comment by XD2333** [comment]
下个版本修复
https://github.com/XD2333/GalTransl/commit/5817bec214b26dac216c733a932ea563e3f91fab

**Comment by Ptilopsis01** [comment]
> 下个版本修复 [5817bec](https://github.com/XD2333/GalTransl/commit/5817bec214b26dac216c733a932ea563e3f91fab)

最新版本这个换cookie的问题好像还是有，并且不能通过上面说的方法解决

**Comment by XD2333** [comment]
试下最新代码有没有解决问题
https://github.com/XD2333/GalTransl/blob/main/GalTransl/Backend/BingGPT4Translate.py

**Comment by Ptilopsis01** [comment]
> 试下最新代码有没有解决问题 https://github.com/XD2333/GalTransl/blob/main/GalTransl/Backend/BingGPT4Translate.py

不行，还是会反复提示这一段
![image](https://github.com/XD2333/GalTransl/assets/93318731/36e7b39f-5883-4e2f-8335-932ff338eba3)

**Comment by SXK485** [comment]
> > 试下最新代码有没有解决问题 https://github.com/XD2333/GalTransl/blob/main/GalTransl/Backend/BingGPT4Translate.py
> 
> 不行，还是会反复提示这一段 ![image](https://private-user-images.githubusercontent.com/93318731/293208873-36e7b39f-5883-4e2f-8335-932ff338eba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDM1ODksIm5iZiI6MTcwNTI0MzI4OSwicGF0aCI6Ii85MzMxODczMS8yOTMyMDg4NzMtMzZlN2IzOWYtNTg4My00ZTJmLTgzMzUtOTMyZmYzMzhlYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0NDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NTQyZTg1N2IyMmU2OGY4MzMxY2UwNjM3M2NlNWVjYjlhZTE4MjU2YmE0MjMzYzRlZmQ5NmVjYzBlZGE1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j1soSTMsz8N1_5Vjz7dPcjPKGNctU4sErokx2yASVKM)

353行，由于`await self._change_cookie()`放在
```
        if len(trans_list_unhit) == 0:
            return []
```
之前，所以当transl_cache存在缓存文件时，每次经过这段逻辑都会导致换cookie，`await self._change_cookie()`放在if判断之后应该能解决问题

**Comment by XD2333** [comment]
> > > 试下最新代码有没有解决问题 https://github.com/XD2333/GalTransl/blob/main/GalTransl/Backend/BingGPT4Translate.py
> > 
> > 
> > 不行，还是会反复提示这一段 ![image](https://private-user-images.githubusercontent.com/93318731/293208873-36e7b39f-5883-4e2f-8335-932ff338eba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDM1ODksIm5iZiI6MTcwNTI0MzI4OSwicGF0aCI6Ii85MzMxODczMS8yOTMyMDg4NzMtMzZlN2IzOWYtNTg4My00ZTJmLTgzMzUtOTMyZmYzMzhlYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE0NDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NTQyZTg1N2IyMmU2OGY4MzMxY2UwNjM3M2NlNWVjYjlhZTE4MjU2YmE0MjMzYzRlZmQ5NmVjYzBlZGE1ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j1soSTMsz8N1_5Vjz7dPcjPKGNctU4sErokx2yASVKM)
> 
> 353行，由于`await self._change_cookie()`放在
> 
> ```
>         if len(trans_list_unhit) == 0:
>             return []
> ```
> 
> 之前，所以当transl_cache存在缓存文件时，每次经过这段逻辑都会导致换cookie，`await self._change_cookie()`放在if判断之后应该能解决问题

感谢，下个版本修正

**Comment by XD2333** [comment]
https://github.com/XD2333/GalTransl/releases/tag/3.6.0

**Comment by Ptilopsis01** [comment]
现在会报另一个错：
``
翻译器：newbing
[2024-01-19 20:25:40,511][INFO]载入 普通字典：01H字典_矫正_译前.txt  145普通词条
[2024-01-19 20:25:40,511][INFO]载入 普通字典：00通用字典_译前.txt  26普通词条
[2024-01-19 20:25:40,512][INFO]载入 普通字典：00通用字典_符号_译后.txt  9普通词条 27条件词条
[2024-01-19 20:25:40,513][INFO]载入 普通字典：00通用字典_译后.txt  1普通词条 6条件词条
[2024-01-19 20:25:40,514][INFO]载入 GPT字典: GPT字典.txt 8普通词条
[2024-01-19 20:25:40,515][INFO]载入 GPT字典: 项目GPT字典.txt 13普通词条
[2024-01-19 20:25:40,515][WARNING]不使用代理
[2024-01-19 20:25:42,491][INFO]->翻译输入：# Glossary
| Src | Dst(/Dst2/..) | Note |
| --- | --- | --- |
| 進 | 进 | player's first name, boy |
| りね | 铃音 | 水名りね's first name, girl |
| 姫佳 | 姬佳 | 当麻姫佳's first name, girl, player's younger sister |
| 舜 | 舜 | 三田舜's first name, boy |

{"id": 46, "name": "【舜】", "src": "こんな感じで"}
{"id": 47, "name": "【りね】", "src": "そうそう、私みたいにね〜。\r\n　って、私は顔と身長だけ！\r\n　成長してるとこはち ゃんと成長してるから！"}
{"id": 48, "name": "【進】", "src": "顔と身長が成長してなかったら、\r\n　それはもう成長してないんでいいんじゃないですか ？"}
{"id": 49, "name": "【りね】", "src": "失礼だよ！\r\n　そんなことないよ！\r\n　私が低く見えるのは、完全に目の錯覚なんだ から！"}
{"id": 50, "src": "物理的な現実まで変えてしまうとは、\r\n半端じゃない目の錯覚だ。"}
{"id": 51, "name": "【姫佳】", "src": "あの……。\r\n　私、余計なことを聞いてしまったのでしょうか？"}
{"id": 52, "name": "【りね】", "src": "そんなことないんだけどね……。\r\n　ロリを誇ればいいのか否定すればいいのか、\r\n　 難しい年頃なのですよ。妹ちゃんもいつかわかる日が来る"}
{"id": 53, "name": "【姫佳】", "src": "そうなんですか"}
{"id": 54, "name": "【進】", "src": "部長の言うことはわかんなくていいからな？"}


[2024-01-19 20:25:42,492][INFO]->请求次数：1
'CBingGPT4Translate' object has no attribute 'chatbot'
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\BingGPT4Translate.py", line 146, in translate
    async for final, response in self.chatbot.ask_stream(
AttributeError: 'CBingGPT4Translate' object has no attribute 'chatbot'
[2024-01-19 20:25:42,495][INFO]Error:'CBingGPT4Translate' object has no attribute 'chatbot', Please wait 30 seconds
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\BingGPT4Translate.py", line 146, in translate
    async for final, response in self.chatbot.ask_stream(
AttributeError: 'CBingGPT4Translate' object has no attribute 'chatbot'
[2024-01-19 20:25:47,498][INFO]->请求次数：2
'CBingGPT4Translate' object has no attribute 'chatbot'
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\BingGPT4Translate.py", line 146, in translate
    async for final, response in self.chatbot.ask_stream(
AttributeError: 'CBingGPT4Translate' object has no attribute 'chatbot'
[2024-01-19 20:25:47,499][INFO]Error:'CBingGPT4Translate' object has no attribute 'chatbot', Please wait 30 seconds
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\BingGPT4Translate.py", line 146, in translate
    async for final, response in self.chatbot.ask_stream(
AttributeError: 'CBingGPT4Translate' object has no attribute 'chatbot'
[2024-01-19 20:25:52,505][INFO]->请求次数：3
'CBingGPT4Translate' object has no attribute 'chatbot'
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\BingGPT4Translate.py", line 146, in translate
    async for final, response in self.chatbot.ask_stream(
AttributeError: 'CBingGPT4Translate' object has no attribute 'chatbot'
[2024-01-19 20:25:52,506][INFO]Error:'CBingGPT4Translate' object has no attribute 'chatbot', Please wait 30 seconds
Traceback (most recent call last):
  File "F:\GalTransl\GalTransl\Backend\BingGPT4Translate.py", line 146, in translate
    async for final, response in self.chatbot.ask_stream(
AttributeError: 'CBingGPT4Translate' object has no attribute 'chatbot'
``

**Comment by XD2333** [comment]
hot fix 了一个版本，在我这已经能跑了，不能的话试下更新依赖
https://github.com/XD2333/GalTransl/releases/tag/3.6.1

**Comment by Ptilopsis01** [comment]
确实可以了，感谢
