### ISSUE TITLE
執行出現以下錯誤訊息

### ISSUE THREAD

**Issue by sauron951** [XD2333/GalTransl#7]
Traceback (most recent call last):
  File "E:\GalTransl-main\GalTransl\Backend\GPT3Translate.py", line 138, in asyncTranslate
    for data in self.chatbot.ask_stream(prompt_req):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\revChatGPT\V3.py", line 203, in ask_stream
    raise t.APIConnectionError(
revChatGPT.typings.APIConnectionError: 401 Unauthorized {
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

Please check if there is a problem with your network connection
Please check that the input is correct, or you can resolve this issue by filing an issue
Project URL: https://github.com/acheong08/ChatGPT
[2023-06-11 23:32:52,157][ERROR]Error:401 Unauthorized {
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
新手使用，出現這個實在不知道如何解決...

**Comment by XD2333** [comment]
删掉多余的key
      - token: sk-yyyyyyyy
        endpoint: ""

**Comment by sauron951** [comment]
照步驟做了，還是出現一樣的錯誤..

**Comment by XD2333** [comment]
如果你的配置文件只有1个key了还是报这个错误，那么首先看你的key是不是官方的key，第三方的key是需要对应修改endpoint的。第二看你这个key是不是有效的

**Comment by sauron951** [comment]
是官方的key，要怎麼知道key是有效的?

**Comment by XD2333** [comment]
https://balance.keya.pw/

**Comment by sauron951** [comment]
查詢是有效的

**Comment by XD2333** [comment]
加下群吧，私聊我你的配置文件，像这种报错一般都是配置文件没写对。
